
/*
 * GET home page.
 */

/* 
 * Default scaffolding generated by Express. We'll keep it, why not.
 */

exports.index = function(req, res){
  if (typeof req.user != 'undefined'){
    if (typeof req.session.jornada == 'undefined'){
      var Jornada  = require('../models/jornada').model;
      new Jornada()
        .query({where:{activa:1}}) 
        .fetch()
        .then(function(model) {
          if (model===null) res.render('inicio', { title: 'PBar' , usuario: req.user}); 
          else {
            req.session.jornada = model.get('id');
            res.render('index', { title: 'PBar' , usuario: req.user});
          }
      });
    } else {
      res.render('index', { title: 'PBar' , usuario: req.user});
    }
  } else {
    res.redirect('/login');
  }
    
};

exports.prueba = function(req, res){
            res.render('prueba', { title: 'Prueba BackboneJS'});
};